"""initial tables

Revision ID: 3a1c62f090ac
Revises: 
Create Date: 2026-05-14 10:53:50.310512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1c62f090ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('urls_shortUrl_key'), 'urls', type_='unique')
    op.create_index(op.f('ix_urls_shortUrl'), 'urls', ['shortUrl'], unique=True)
    op.create_index(op.f('ix_urls_tmp_code'), 'urls', ['tmp_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_tmp_code'), table_name='urls')
    op.drop_index(op.f('ix_urls_shortUrl'), table_name='urls')
    op.create_unique_constraint(op.f('urls_shortUrl_key'), 'urls', ['shortUrl'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
