"""add is_active to urls

Revision ID: 5e5c99d09edd
Revises: 3a1c62f090ac
Create Date: 2026-05-14 11:00:37.641918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5c99d09edd'
down_revision: Union[str, Sequence[str], None] = '3a1c62f090ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('urls_shortUrl_key'), 'urls', type_='unique')
    op.create_index(op.f('ix_urls_shortUrl'), 'urls', ['shortUrl'], unique=True)
    op.create_index(op.f('ix_urls_tmp_code'), 'urls', ['tmp_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_tmp_code'), table_name='urls')
    op.drop_index(op.f('ix_urls_shortUrl'), table_name='urls')
    op.create_unique_constraint(op.f('urls_shortUrl_key'), 'urls', ['shortUrl'], postgresql_nulls_not_distinct=False)
    op.drop_column('urls', 'is_active')
    # ### end Alembic commands ###
