"""add testCol to urls

Revision ID: dc51cc4316da
Revises: 5e5c99d09edd
Create Date: 2026-05-19 19:24:08.005096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc51cc4316da'
down_revision: Union[str, Sequence[str], None] = '5e5c99d09edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('testCol', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'testCol')
    # ### end Alembic commands ###
